language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - LINT_TEST=1
        - SYMFONY="4.0.*"
    - php: 7.2
      env:
        - SYMFONY="3.0.*"

sudo: false

before_script:
# Init php
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH

# Install composer dependencies
  - composer validate
  - composer require symfony/console:$SYMFONY symfony/yaml:$SYMFONY symfony/process:$SYMFONY symfony/filesystem:$SYMFONY --no-update
  - composer install
  - composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o

script:
  - vendor/bin/phpunit --color tests
  - if [[ $LINT_TEST ]]; then composer run-script lint; fi
